// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartRecruitment_Project.Data;

#nullable disable

namespace SmartRecruitment_Project.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260808064028_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartRecruitment_Project.Models.Application", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppliedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("JobSeekerProfileId")
                        .HasColumnType("int");

                    b.Property<int>("JobVacancyId")
                        .HasColumnType("int");

                    b.Property<decimal>("MatchScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("JobSeekerProfileId");

                    b.HasIndex("JobVacancyId", "JobSeekerProfileId")
                        .IsUnique();

                    b.ToTable("Applications", (string)null);
                });

            modelBuilder.Entity("SmartRecruitment_Project.Models.ContactRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApplicationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.ToTable("ContactRequests", (string)null);
                });

            modelBuilder.Entity("SmartRecruitment_Project.Models.CvDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<int>("JobSeekerProfileId")
                        .HasColumnType("int");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("JobSeekerProfileId")
                        .IsUnique();

                    b.ToTable("CvDocuments", (string)null);
                });

            modelBuilder.Entity("SmartRecruitment_Project.Models.EmployerProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Description")
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.Property<string>("Location")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Website")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("EmployerProfiles", (string)null);
                });

            modelBuilder.Entity("SmartRecruitment_Project.Models.JobSeekerProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EducationLevel")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Location")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Summary")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("YearsOfExperience")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("JobSeekerProfiles", (string)null);
                });

            modelBuilder.Entity("SmartRecruitment_Project.Models.JobSeekerSkill", b =>
                {
                    b.Property<int>("JobSeekerProfileId")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.HasKey("JobSeekerProfileId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("JobSeekerSkills", (string)null);
                });

            modelBuilder.Entity("SmartRecruitment_Project.Models.JobVacancy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("nvarchar(3000)");

                    b.Property<int>("EmployerProfileId")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("MinimumExperienceYears")
                        .HasColumnType("int");

                    b.Property<int>("RequiredEducationLevel")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EmployerProfileId");

                    b.ToTable("JobVacancies", (string)null);
                });

            modelBuilder.Entity("SmartRecruitment_Project.Models.JobVacancySkill", b =>
                {
                    b.Property<int>("JobVacancyId")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.HasKey("JobVacancyId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("JobVacancySkills", (string)null);
                });

            modelBuilder.Entity("SmartRecruitment_Project.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("SmartRecruitment_Project.Models.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.ToTable("Skills", (string)null);
                });

            modelBuilder.Entity("SmartRecruitment_Project.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("SmartRecruitment_Project.Models.Application", b =>
                {
                    b.HasOne("SmartRecruitment_Project.Models.JobSeekerProfile", "JobSeekerProfile")
                        .WithMany("Applications")
                        .HasForeignKey("JobSeekerProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartRecruitment_Project.Models.JobVacancy", "JobVacancy")
                        .WithMany("Applications")
                        .HasForeignKey("JobVacancyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("JobSeekerProfile");

                    b.Navigation("JobVacancy");
                });

            modelBuilder.Entity("SmartRecruitment_Project.Models.ContactRequest", b =>
                {
                    b.HasOne("SmartRecruitment_Project.Models.Application", "Application")
                        .WithMany("ContactRequests")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("SmartRecruitment_Project.Models.CvDocument", b =>
                {
                    b.HasOne("SmartRecruitment_Project.Models.JobSeekerProfile", "JobSeekerProfile")
                        .WithOne("CvDocument")
                        .HasForeignKey("SmartRecruitment_Project.Models.CvDocument", "JobSeekerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobSeekerProfile");
                });

            modelBuilder.Entity("SmartRecruitment_Project.Models.EmployerProfile", b =>
                {
                    b.HasOne("SmartRecruitment_Project.Models.User", "User")
                        .WithOne("EmployerProfile")
                        .HasForeignKey("SmartRecruitment_Project.Models.EmployerProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartRecruitment_Project.Models.JobSeekerProfile", b =>
                {
                    b.HasOne("SmartRecruitment_Project.Models.User", "User")
                        .WithOne("JobSeekerProfile")
                        .HasForeignKey("SmartRecruitment_Project.Models.JobSeekerProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartRecruitment_Project.Models.JobSeekerSkill", b =>
                {
                    b.HasOne("SmartRecruitment_Project.Models.JobSeekerProfile", "JobSeekerProfile")
                        .WithMany("JobSeekerSkills")
                        .HasForeignKey("JobSeekerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartRecruitment_Project.Models.Skill", "Skill")
                        .WithMany("JobSeekerSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobSeekerProfile");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("SmartRecruitment_Project.Models.JobVacancy", b =>
                {
                    b.HasOne("SmartRecruitment_Project.Models.EmployerProfile", "EmployerProfile")
                        .WithMany("JobVacancies")
                        .HasForeignKey("EmployerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmployerProfile");
                });

            modelBuilder.Entity("SmartRecruitment_Project.Models.JobVacancySkill", b =>
                {
                    b.HasOne("SmartRecruitment_Project.Models.JobVacancy", "JobVacancy")
                        .WithMany("JobVacancySkills")
                        .HasForeignKey("JobVacancyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartRecruitment_Project.Models.Skill", "Skill")
                        .WithMany("JobVacancySkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobVacancy");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("SmartRecruitment_Project.Models.Notification", b =>
                {
                    b.HasOne("SmartRecruitment_Project.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartRecruitment_Project.Models.Application", b =>
                {
                    b.Navigation("ContactRequests");
                });

            modelBuilder.Entity("SmartRecruitment_Project.Models.EmployerProfile", b =>
                {
                    b.Navigation("JobVacancies");
                });

            modelBuilder.Entity("SmartRecruitment_Project.Models.JobSeekerProfile", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("CvDocument");

                    b.Navigation("JobSeekerSkills");
                });

            modelBuilder.Entity("SmartRecruitment_Project.Models.JobVacancy", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("JobVacancySkills");
                });

            modelBuilder.Entity("SmartRecruitment_Project.Models.Skill", b =>
                {
                    b.Navigation("JobSeekerSkills");

                    b.Navigation("JobVacancySkills");
                });

            modelBuilder.Entity("SmartRecruitment_Project.Models.User", b =>
                {
                    b.Navigation("EmployerProfile");

                    b.Navigation("JobSeekerProfile");

                    b.Navigation("Notifications");
                });
#pragma warning restore 612, 618
        }
    }
}
